version: "3"

services:
    db:
        build:
            context: ./db
            dockerfile: Dockerfile
        ports:
            - ${PGPORT}:26257
        environment:
            POSTGRES_USER: ${PGUSER}
            POSTGRES_PASSWORD: ${PGPASSWORD}
            POSTGRES_DB: ${PGDATABASE}
